-- =============================================================
-- fit-proof 完全スキーマ定義
-- テーブル作成順序はFK依存関係に基づく
-- profiles.id を参照するFK列は全て「user_id」に統一
-- =============================================================

-- 1. profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  display_name text,
  role text check (role in ('admin', 'client')) default 'client',

  updated_at timestamp with time zone,
  past_submission_days integer default 7,
  future_submission_days integer default 7,
  deadline_mode text check (deadline_mode in ('none', 'mark')) default 'none',
  show_duplicate_to_user boolean default false,
  total_reps integer default 0,
  shield_stock integer default 0,
  perfect_week_count integer default 0,
  revival_success_count integer default 0,
  gamification_settings jsonb,
  video_retention_days integer default 30,

  constraint username_length check (char_length(display_name) >= 3)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

create policy "Admins can update any profile." on profiles
  for update using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );


-- 2. authorized_users
create table authorized_users (
  email text primary key,
  role text check (role in ('admin', 'client')) default 'client',
  user_id uuid references profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table authorized_users enable row level security;

create policy "Authorized users are viewable by everyone." on authorized_users
  for select using (true);

create policy "Admins can manage authorized users." on authorized_users
  for all using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );


-- 4. submission_items
create table submission_items (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  effective_from timestamp with time zone default timezone('utc'::text, now()) not null,
  effective_to timestamp with time zone default null
);

alter table submission_items enable row level security;

create policy "Users can view own submission items or admins can view all." on submission_items
  for select using (
    auth.uid() = user_id
    or exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

create policy "Admins can manage submission items." on submission_items
  for all using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );


-- 5. submissions
create table submissions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  type text check (type in ('video', 'comment', 'shield')) not null,
  r2_key text,
  thumbnail_url text,
  duration integer,
  comment_text text,
  status text check (status in ('success', 'fail', 'excused')) default 'success',
  target_date date,
  submission_item_id bigint references submission_items(id) on delete set null,
  file_name text,
  reviewed_at timestamp with time zone,
  is_late boolean default false,
  reps integer,
  is_revival boolean default false,
  video_size bigint,
  video_hash text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table submissions enable row level security;

create policy "Submissions are viewable by everyone." on submissions
  for select using (true);

create policy "Users can insert their own submissions." on submissions
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own submissions." on submissions
  for update using (auth.uid() = user_id);

create policy "Admins can update any submission." on submissions
  for update using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

create policy "Users can delete their own submissions." on submissions
  for delete using (auth.uid() = user_id);

create policy "Admins can delete any submission." on submissions
  for delete using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );


-- 6. submission_rules
create table submission_rules (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  rule_type text check (rule_type in ('deadline', 'target_day', 'rest_day', 'group')) not null,
  scope text check (scope in ('monthly', 'weekly', 'daily')) not null,
  day_of_week smallint check (day_of_week between 0 and 6),
  specific_date date,
  value text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  effective_from timestamp with time zone default timezone('utc'::text, now()) not null,
  group_id uuid default null,
  group_required_count integer default null,
  effective_to timestamp with time zone default null
);

alter table submission_rules enable row level security;

create policy "Admins can manage submission rules." on submission_rules
  for all using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

create policy "Users can view their own submission rules." on submission_rules
  for select using (auth.uid() = user_id);


-- 7. admin_comments
create table admin_comments (
  id uuid default gen_random_uuid() primary key,
  submission_id bigint not null unique references submissions(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade not null,
  content text,
  read_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table admin_comments enable row level security;

create policy "Comment visible to author or submission owner." on admin_comments
  for select using (
    auth.uid() = user_id
    or exists (
      select 1 from submissions
      where submissions.id = submission_id
      and submissions.user_id = auth.uid()
    )
  );

create policy "Admins can manage admin comments." on admin_comments
  for all using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

create policy "Users can update comments on their own submissions." on admin_comments
  for update using (
    exists (
      select 1 from submissions
      where submissions.id = submission_id
      and submissions.user_id = auth.uid()
    )
  );
