-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  display_name text,
  role text check (role in ('admin', 'client')) default 'client',
  streak_count integer default 0,
  updated_at timestamp with time zone,

  constraint username_length check (char_length(display_name) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Deadlines table
create table deadlines (
  id bigint generated by default as identity primary key,
  title text not null,
  target_time time without time zone not null,
  frequency text check (frequency in ('daily', 'weekly', 'monthly')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table deadlines enable row level security;

-- Everyone can view deadlines (for now)
create policy "Deadlines are viewable by everyone." on deadlines
  for select using (true);

-- Only admins should be able to insert/update (logic to be refined later)
create policy "Enable read access for all users" on deadlines for select using (true);


-- Submissions table
create table submissions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  type text check (type in ('video', 'comment')) not null,
  r2_key text, -- For video type
  thumbnail_url text, -- For video type
  duration integer, -- For video type (seconds)
  comment_text text, -- For comment type or additional info
  status text check (status in ('success', 'fail', 'excused')) default 'success',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table submissions enable row level security;

create policy "Submissions are viewable by everyone." on submissions
  for select using (true);

create policy "Users can insert their own submissions." on submissions
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own submissions." on submissions
  for update using (auth.uid() = user_id);
