-- =============================================================
-- gamification_setting_versions.sql
-- ゲーミフィケーション設定の時系列バージョン管理テーブル
-- 1. テーブル DDL + RLS
-- 2. 既存データのバックフィル
-- 3. save / reactivate RPC 関数
-- =============================================================

-- Step 1: テーブル作成
CREATE TABLE IF NOT EXISTS gamification_setting_versions (
    id                      bigint generated by default as identity primary key,
    user_id                 uuid references profiles(id) on delete cascade not null,
    condition_type          text check (condition_type in ('straight_count', 'monthly_all'))
                                not null default 'straight_count',
    straight_count          integer not null default 1,
    allow_shield            boolean not null default false,
    allow_revival           boolean not null default false,
    allow_late              boolean not null default true,
    use_target_days         boolean not null default true,
    custom_required_days    integer not null default 7,
    effective_from          date not null default current_date,
    effective_to            date default null,
    created_at              timestamp with time zone default now() not null,
    constraint chk_effective_range check (
        effective_to IS NULL OR effective_to >= effective_from
    )
);

-- 1ユーザーにつき active バージョン（effective_to IS NULL）は最大1件
CREATE UNIQUE INDEX IF NOT EXISTS idx_gamification_setting_versions_active
    ON gamification_setting_versions (user_id)
    WHERE effective_to IS NULL;

-- Step 2: RLS
ALTER TABLE gamification_setting_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own gamification setting versions." ON gamification_setting_versions
    FOR SELECT USING (
        auth.uid() = user_id
        OR EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role = 'admin'
        )
    );

CREATE POLICY "Admins can manage gamification setting versions." ON gamification_setting_versions
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role = 'admin'
        )
    );

-- Step 3: 既存データのバックフィル（冪等）
-- 各ユーザーの gamification_settings JSONB から初期バージョンを作成
-- allow_late=true → allow_revival=true の正規化はバックフィルでは行わない（既存値を忠実に保存）
INSERT INTO gamification_setting_versions (user_id, condition_type, straight_count, allow_shield, allow_revival, allow_late, use_target_days, custom_required_days, effective_from)
SELECT
    p.id,
    COALESCE(p.gamification_settings->'shield'->>'condition_type', 'straight_count'),
    COALESCE((p.gamification_settings->'shield'->>'straight_count')::integer, 1),
    -- 注意: allow_shield は shield.enabled（表示トグル）ではなく straight.allow_shield（計算ロジック）から取得
    COALESCE((p.gamification_settings->'straight'->>'allow_shield')::boolean, false),
    -- allow_revival: 既存値をそのまま保存（正規化しない）
    COALESCE((p.gamification_settings->'straight'->>'allow_revival')::boolean, false),
    COALESCE((p.gamification_settings->'straight'->>'allow_late')::boolean, true),
    COALESCE((p.gamification_settings->'straight'->>'use_target_days')::boolean, true),
    COALESCE((p.gamification_settings->'straight'->>'custom_required_days')::integer, 7),
    '2020-01-01'::date
FROM profiles p
ON CONFLICT DO NOTHING;

-- Step 4: save_gamification_version RPC 関数
CREATE OR REPLACE FUNCTION save_gamification_version(
    p_user_id uuid,
    p_condition_type text DEFAULT 'straight_count',
    p_straight_count integer DEFAULT 1,
    p_allow_shield boolean DEFAULT false,
    p_allow_revival boolean DEFAULT false,
    p_allow_late boolean DEFAULT true,
    p_use_target_days boolean DEFAULT true,
    p_custom_required_days integer DEFAULT 7
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    -- allow_late=true なら allow_revival を強制 true に正規化
    IF p_allow_late THEN
        p_allow_revival := true;
    END IF;

    -- 現在の active バージョンを close
    UPDATE gamification_setting_versions
    SET effective_to = GREATEST(current_date, effective_from)
    WHERE user_id = p_user_id AND effective_to IS NULL;

    -- 新バージョンを insert
    INSERT INTO gamification_setting_versions (
        user_id, condition_type, straight_count,
        allow_shield, allow_revival, allow_late,
        use_target_days, custom_required_days,
        effective_from, effective_to
    ) VALUES (
        p_user_id, p_condition_type, p_straight_count,
        p_allow_shield, p_allow_revival, p_allow_late,
        p_use_target_days, p_custom_required_days,
        current_date, NULL
    );
END;
$$;

-- Step 5: reactivate_gamification_version RPC 関数
CREATE OR REPLACE FUNCTION reactivate_gamification_version(
    p_version_id bigint
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_user_id uuid;
BEGIN
    -- 対象バージョンの user_id を取得
    SELECT user_id INTO v_user_id
    FROM gamification_setting_versions
    WHERE id = p_version_id;

    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Version not found: %', p_version_id;
    END IF;

    -- 現在の active バージョンがあれば close
    UPDATE gamification_setting_versions
    SET effective_to = current_date
    WHERE user_id = v_user_id AND effective_to IS NULL;

    -- 対象バージョンを再有効化
    UPDATE gamification_setting_versions
    SET effective_to = NULL
    WHERE id = p_version_id;
END;
$$;
